### ISSUE TITLE
ValueError: time data 

### ISSUE THREAD

**Issue by nvjacobo** [ucsdsysnet/trufflehunter#5]
When run: 

python3 trufflehunter.py --domain=github.com

```
Traceback (most recent call last):
  File "trufflehunter.py", line 88, in <module>
    main()
  File "trufflehunter.py", line 85, in main
    _ = searcher.runBaseSearcher()
  File "/home/nvjacobo/trufflehunter/trufflehunter/core/continuous_search.py", line 149, in runBaseSearcher
    search_results = base_searcher.searchForDomains()
  File "/home/nvjacobo/trufflehunter/trufflehunter/core/continuous_search.py", line 116, in searchForDomains
    search_results += dns_lib.multipleDigRequests(self.scripts[resolver], self.hostname, resolver, loc=loc, dig_cmd=self.dig_cmd)
  File "/home/nvjacobo/trufflehunter/trufflehunter/core/dns_lib.py", line 317, in multipleDigRequests
    r = DigParser(response, ts, loc)
  File "/home/nvjacobo/trufflehunter/trufflehunter/core/dns_lib.py", line 146, in __init__
    self.parse(dig_output, ts, loc)
  File "/home/jacobo/trufflehunter/trufflehunter/core/dns_lib.py", line 137, in parse
    self.dig_ts = datetime.strptime(day + ' ' + year + ' ' + timezone, '%c %Z')
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data 'lun oct 26 18:56:31 2020 CST' does not match format '%c %Z'
```

Setup: 
- Debian 10 
- Python Python 3.7.3 

Thanks

**Comment by alexliu0809** [comment]
We will look into it. Thank you for your feedback.

**Comment by Audrey-Randall** [comment]
What version of dig do you have installed?

**Comment by Audrey-Randall** [comment]
Oh - I think I see. "lun" as a weekday doesn't match the format specifier because it isn't an English weekday, it's Spanish right? I'll look into making this work for non-English dig printouts.

**Comment by nvjacobo** [comment]
> Oh - I think I see. "lun" as a weekday doesn't match the format specifier because it isn't an English weekday, it's Spanish right? I'll look into making this work for non-English dig printouts.

Hi, 

Yes . My locale is set Spanish. 

Tried locale set in english and it works fine.

Thanks, Jacobo

**Comment by alexliu0809** [comment]
This issue will now be closed.

Solution: set your locale to English if it is not.
