### ISSUE TITLE
TypeError: __init__() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by bortzmeyer** [ucsdsysnet/trufflehunter#6]
```
% python3 trufflehunter.py --domain=bortzmeyer.org
Runtime Configs: number_of_attempts_per_domain=10, resolvers_to_try=1.1.1.1 9.9.9.9, verbose=False

Traceback (most recent call last):
  File "trufflehunter.py", line 92, in <module>
    main()
  File "trufflehunter.py", line 89, in main
    _ = searcher.runBaseSearcher()
  File "/home/stephane/tmp/trufflehunter/trufflehunter/core/continuous_search.py", line 156, in runBaseSearcher
    search_results = base_searcher.searchForDomains()
  File "/home/stephane/tmp/trufflehunter/trufflehunter/core/continuous_search.py", line 119, in searchForDomains
    search_results += dns_lib.multipleDigRequests(self.scripts[resolver], self.hostname, resolver, loc=loc, dig_cmd=self.dig_cmd)
  File "/home/stephane/tmp/trufflehunter/trufflehunter/core/dns_lib.py", line 319, in multipleDigRequests
    r = KdigParser(response, ts, loc)
TypeError: __init__() takes 3 positional arguments but 4 were given
```

```
% python3 --version 
Python 3.7.3
```

**Comment by bortzmeyer** [comment]
kdig code seems quite broken, removing kdig and using dig works.

**Comment by Audrey-Randall** [comment]
Thanks for flagging - I will look into this shortly.

**Comment by alexliu0809** [comment]
I don’t think we have a good support for kdig. Please try using `dig` instead and let us know if it works

**Comment by bortzmeyer** [comment]
> I don’t think we have a good support for kdig. Please try using `dig` instead and let us know if it works

It works, I reported it two comments above. (I had to remove kdig because I don't see an option in trufflehunter to unselect it)

**Comment by alexliu0809** [comment]
Sorry for the inconvenience. We will remove support for `kdig` in our later version
